import pyautogui
import time
# coor = pyautogui.locateOnScreen('opera2.jpg',grayscale=True, confidence=0.7)
# coor_center = pyautogui.center(coor)
# # print(coor_center)
# pyautogui.click((coor_center.x),(coor_center.y))
# time.sleep(5)
# coor = pyautogui.locateOnScreen('input.jpg',grayscale=True, confidence=0.9)
# coor_center = pyautogui.center(coor)
# pyautogui.click((coor_center.x)+50,(coor_center.y))
# pyautogui.typewrite("facebook.com")
# # pyautogui.press('enter')
# pyautogui.typewrite("\n")
# time.sleep(5)
# # pyautogui.typewrite("hoa363147@gmail.com")
# # time.sleep(3)
# # pyautogui.click(x=822, y=368)
# # pyautogui.typewrite("xuanhoa123456")
# # pyautogui.typewrite("\n")
# # time.sleep(5)
# # coor = pyautogui.locateOnScreen('home.jpg',grayscale=True, confidence=0.7)
# # coor_center = pyautogui.center(coor)
# # pyautogui.click((coor_center.x),(coor_center.y))
# # time.sleep(5)
# coor = pyautogui.locateOnScreen('tus2.jpg', grayscale=True, confidence=0.9)
# coor_center = pyautogui.center(coor)
# # print(coor_center)
# pyautogui.click((coor_center.x) + 50, (coor_center.y))
# time.sleep(3)
# with open("content.txt", "r") as file:
#     lines = file.readlines()
# for line in lines:
#     pyautogui.typewrite(line.strip())  # strip() để loại bỏ khoảng trắng dư thừa ở đầu và cuối dòng
#     coor = pyautogui.locateOnScreen('checkin.jpg', grayscale=True, confidence=0.9)
#     coor_center = pyautogui.center(coor)
#     pyautogui.click((coor_center.x), (coor_center.y))
#     time.sleep(5)
#     pyautogui.typewrite("dai hoc quang binh")
#     time.sleep(3)
#     coor = pyautogui.locateOnScreen('dhqb2.jpg', grayscale=True, confidence=0.7)
#     coor_center = pyautogui.center(coor)
#     pyautogui.click((coor_center.x), (coor_center.y))
#     time.sleep(5)
#     coor = pyautogui.locateOnScreen('dangtus.jpg', grayscale=True, confidence=0.9)
#     coor_center = pyautogui.center(coor)
#     pyautogui.click((coor_center.x),(coor_center.y))
#     time.sleep(5)
#     pyautogui.press("enter")  # Nhấn phím Enter để chuyển sang dòng mới
#     # Đợi một chút trước khi gõ dòng tiếp theo
#     time.sleep(2)

def dangbai(content):
    coor = pyautogui.locateOnScreen('tus2.jpg', grayscale=True, confidence=0.9)
    coor_center = pyautogui.center(coor)
    # print(coor_center)
    pyautogui.click((coor_center.x) + 50, (coor_center.y))
    time.sleep(3)
    pyautogui.write(content)
    coor = pyautogui.locateOnScreen('checkin.jpg', grayscale=True, confidence=0.9)
    coor_center = pyautogui.center(coor)
    pyautogui.click((coor_center.x), (coor_center.y))
    time.sleep(5)
    pyautogui.typewrite("dai hoc quang binh")
    time.sleep(3)
    coor = pyautogui.locateOnScreen('dhqb2.jpg', grayscale=True, confidence=0.7)
    coor_center = pyautogui.center(coor)
    pyautogui.click((coor_center.x), (coor_center.y))
    time.sleep(5)
    coor = pyautogui.locateOnScreen('dangtus.jpg', grayscale=True, confidence=0.9)
    coor_center = pyautogui.center(coor)
    pyautogui.click((coor_center.x), (coor_center.y))
    time.sleep(5)
def main():
    coor = pyautogui.locateOnScreen('opera2.jpg', grayscale=True, confidence=0.7)
    coor_center = pyautogui.center(coor)
    # print(coor_center)
    pyautogui.click((coor_center.x), (coor_center.y))
    time.sleep(5)
    coor = pyautogui.locateOnScreen('input.jpg', grayscale=True, confidence=0.9)
    coor_center = pyautogui.center(coor)
    pyautogui.click((coor_center.x) + 50, (coor_center.y))
    pyautogui.typewrite("facebook.com")
    # pyautogui.press('enter')
    pyautogui.typewrite("\n")
    time.sleep(5)
    with open("content.txt", "r") as file:
        lines = file.readlines()
    for line in lines:
        dangbai(line)
        # pyautogui.press("enter")
        time.sleep(1)
if __name__ == '__main__':
    main()