import pyautogui
import time
coor = pyautogui.locateOnScreen('opera2.jpg',grayscale=True, confidence=0.7)
coor_center = pyautogui.center(coor)
# print(coor_center)
pyautogui.click((coor_center.x),(coor_center.y))
time.sleep(5)
coor = pyautogui.locateOnScreen('input.jpg',grayscale=True, confidence=0.9)
coor_center = pyautogui.center(coor)
pyautogui.click((coor_center.x)+50,(coor_center.y))
pyautogui.typewrite("facebook.com")
# pyautogui.press('enter')
pyautogui.typewrite("\n")
time.sleep(5)
pyautogui.typewrite("hoa363147@gmail.com")
time.sleep(3)
pyautogui.click(x=822, y=368)
pyautogui.typewrite("xuanhoa123456")
pyautogui.typewrite("\n")
time.sleep(5)
coor = pyautogui.locateOnScreen('home.jpg',grayscale=True, confidence=0.7)
coor_center = pyautogui.center(coor)
pyautogui.click((coor_center.x),(coor_center.y))
time.sleep(5)
coor = pyautogui.locateOnScreen('tus2.jpg',grayscale=True, confidence=0.9)
coor_center = pyautogui.center(coor)
print(coor_center)
pyautogui.click((coor_center.x)+50,(coor_center.y))
time.sleep(3)
pyautogui.typewrite("BAI DANG SO 1")
time.sleep(2)
coor = pyautogui.locateOnScreen('dangtus.jpg', grayscale=True, confidence=0.9)
coor_center = pyautogui.center(coor)
pyautogui.click((coor_center.x),(coor_center.y))
time.sleep(5)